### ISSUE TITLE
Binary not working

### ISSUE THREAD

**Issue by ganesh-katakam-T18451** [dailymotion-oss/octopilot#101]
Hi guys,

I'm trying to use octopilot and downloaded the binary from the latest release. The downloaded file is neither a zip file nor an executable one. Is there any guide to setup octopilot. I'm trying this on Mac.

**Comment by vbehar** [comment]
Hi,

are you using an ARM-based Mac? (M1 chipset) We don't have a binary for M1 yet, so you can either:
- build it locally - `go get github.com/dailymotion-oss/octopilot` should be enough
- or wait until tomorrow: I'll update our build process to produce a "universal" mac binary that works for both arm and amd

**Comment by ganesh-katakam-T18451** [comment]
It is not an M1 chipset Mac. Is the Github release page the only source to download the binary? When I dowloaded the file from Github and saw the info, it is showing as a Document file in Mac.

**Comment by vbehar** [comment]
hum that's strange, here is what I get when I download this file https://github.com/dailymotion-oss/octopilot/releases/download/v1.0.9/octopilot_1.0.9_darwin_amd64 :

<img width="1183" alt="Capture d’écran 2021-11-11 à 10 28 19" src="https://user-images.githubusercontent.com/6251/141273521-c0c2be73-8235-4fca-8e52-1c85b40e6c83.png">

**Comment by ganesh-katakam-T18451** [comment]
After moving the file to /usr/local/bi , now I'm able to run octopilot

**Comment by vbehar** [comment]
ok perfect, then I'm closing this issue. feel free to open a new one if you need help!
