### ISSUE TITLE
[Feature] Checkout branch as configurable flag

### ISSUE THREAD

**Issue by ganesh-katakam-T18451** [dailymotion-oss/octopilot#104]
Hello @vbehar 

Currently octopilot is checking out from the master/main branch and creating a new branch. We have a support for providing a different branch as base for PR. I would like to also have a similar support while checking out. I use the same repository for multiple applications so if I want to use octopilot for the application which is in some other branch I was not able to do that. I couldn't find any solution for this. If there is no existing solution, consider this as a feature request. Thanks 😊

**Comment by vbehar** [comment]
Hi,

you can configure the branch to checkout while cloning using the `branch` parameter on a repo, such as

```
$ octopilot --repo "my-github-org/my-repo(branch=whatever)" ...
```

see https://dailymotion-oss.github.io/octopilot/v1.0.10/index.html#static for more details.

Does this answer your question?

**Comment by ganesh-katakam-T18451** [comment]
I missed the branch option in the repo flag, this will be enough. Thanks @vbehar 🤩

**Comment by vbehar** [comment]
ok perfect, I'll close this issue then, and feel free to open a new one if you need anything!
