### ISSUE TITLE
Add support for github enterprise 

### ISSUE THREAD

**Issue by samj1912** [dailymotion-oss/octopilot#164]
go-github supports GHE via it's NewEnterpriseClient helper which returns a client compatible with NewClient. octopilot should accept github enterprise base and upload urls to allow for this behavior.

**Comment by ahothan** [comment]
+1
I was trying to use octopilot with an Enterprise git only to find it was not supported...
is there any interest in supporting private github?

**Comment by vbehar** [comment]
Hi @ahothan, yes sure. would you be open to create a pull request?

**Comment by ahothan** [comment]
@vbehar
thanks for confirming interest, I wanted to know ahead of time before embarking on updating the doc. 
I actually have a fork that adds support for a private github url, seems to be working so far but I'd like to test a bit more.
I will submit a PR hopefully soon.

**Comment by vbehar** [comment]
perfect, feel free to open it when you're ready

**Comment by ahothan** [comment]
Thanks for getting this in @vbehar 
I think you can close this issue
