### ISSUE TITLE
Feature request: PR Metadata Output

### ISSUE THREAD

**Issue by jashandeep-sohi** [dailymotion-oss/octopilot#295]
# Problem

I find myself needing the ID/number of the PRs created by `octopilot` for further customization in my CI/CD pipelines. Specifically, this is in the context of a GitOps style CD pipeline, where a push/commit to the application "source" repo creates PRs via `octopilot` in a "deploy" repo. I'm trying to create a status update (via the Statues API) on the originating commit (in the "source" repo) that links to the PR in the "deploy" repo. This is mostly for easier traceability and UX, so I don't really need to track the actual state of the PR. Just the link.

# Possible solutions

- This gets baked into `octopilot`. Personally, I don't think this functionality belongs in `ocotpilot` because it's too bespoke and will be hard to express using command line flags. Maybe I'm wrong here.
- If `octopilot` could output a list of PRs it's created/modified (in a structured JSON format), I could use that make any further customization with those PRs as needed with some external tool/script.
- Parse STDOUT :vomiting_face:  and pass that to a script.

I don't know, is there some other way of doing this?

**Comment by vbehar** [comment]
I like option 2. A well defined JSON (or yaml) file with the summary of what has been done. Easy to parse

**Comment by jashandeep-sohi** [comment]
Something like this should work for my use case

```yaml

updated:
 - owner: string
   repo: string
   number: int
   nodeId: string (needed by graphql APIs)
   url: URL

failed:
 - owner: string
   repo: string
   error: string
```

**Comment by vbehar** [comment]
implemented in https://github.com/dailymotion-oss/octopilot/pull/297
