### ISSUE TITLE
[Feature] Fail if there is no PR in append Strategy

### ISSUE THREAD

**Issue by ylorenzati** [dailymotion-oss/octopilot#40]
Hello @vbehar and thanks for this tool

I would like to contribute by adding something that I need.
When using the append strategy, I would like(expect) octopilot to fail if there it can't find the PR

I can think of two way to implements this
* It's kind of a bug and we make that the new default
* by adding some new param (--strategy-append-fail-if-nopr)

If you agree with one of this approach, please tell me, and I provide a PR soon with this

Regards

**Comment by vbehar** [comment]
Hi,

I'm glad that you find it useful!

I like the current behavior because it means we don't need to check if there is a PR or not before running octopilot (to select the right strategy). If you need it to fail if there is no existing PR, I think adding a new flag is a good option.

thanks!
